In [28]:
import cv2
import numpy as np

# Load the image
img = cv2.imread(r'E:\Phone\WhatsApp Images\IMG-20210925-WA0097.jpg')

# Resize the image to fit the screen
height, width, _ = img.shape
max_size = max(height, width)
if max_size > 1000:
    scale = 1000 / max_size
    img = cv2.resize(img, (0, 0), fx=scale, fy=scale)

# Convert to grayscale
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Perform edge detection using the Canny algorithm
edges = cv2.Canny(gray, 50, 150, apertureSize=3)

# Apply Hough Line Transform to detect lines in the image
# rho=1, theta=np.pi/180, and threshold=150. 
# This means that lines will be detected with a resolution of 1 pixel and 1 degree, 
# and a line will be detected if it has at least 150 votes
lines = cv2.HoughLines(edges, 1, np.pi/180, 120)

#line is a tuple  of (rho, theta) which is it's polar coordinates

print(lines)

# Draw the detected lines on the original image
for line in lines:
    rho, theta = line[0]
    a = np.cos(theta)
    b = np.sin(theta)
    x0 = a * rho
    y0 = b * rho
    x1 = int(x0 + 1000 * (-b))
    y1 = int(y0 + 1000 * (a))
    x2 = int(x0 - 1000 * (-b))
    y2 = int(y0 - 1000 * (a))
    cv2.line(img, (x1, y1), (x2, y2), (0, 0, 255), 1)

# Display the result
cv2.imshow('Lines', img)
cv2.waitKey(0)
cv2.destroyAllWindows()


[[[274.          1.5882496]]

 [[404.          1.5882496]]

 [[202.          1.5358897]]

 [[474.          1.4835298]]

 [[393.          1.6231562]]

 [[509.          1.5707964]]

 [[392.          1.6057029]]]
